services:
  rust-server:
    image: didstopia/rust-server:latest
    container_name: rust-server
    env_file:
      - .env
    ports:
      - "28015:28015"
      - "28016:28016"
    volumes:
      - ./rust-data:/steamcmd/rust
