services:
  rust-server:
    image: didstopia/rust-server:latest
    container_name: rust-server
    env_file:
      - .env
    ports:
      - "28015:28015/tcp"
      - "28015:28015/udp"
      - "28016:28016"
      - "28017:28017/tcp"
      - "28017:28017/udp"
      - "28082:28082"
    volumes:
      - ./rust-data:/steamcmd/rust
